#ifndef __PINS_H_
#define __PINS_H_

typedef enum {
	PIN_OLED_SCLK,
	PIN_OLED_SDI,
	PIN_OLED_CS,
	PIN_OLED_RS,
	PIN_OLED_RW,
	PIN_OLED_E,
	PIN_OLED_RS2,
	PIN_DEBUG_LED,
	PIN_LED_DRIVER_GSCLK,
	PIN_LED_DRIVER_LAT,
	PIN_LED_DRIVER_SCK,
	PIN_LED_DRIVER_SIN,
	PIN_BUTTON,
} Pin_T;


#define PIN_LED_DRIVER_GSCLK_PORT 1
#define OLED_GPIO_PORT 1
#define PIN_LED_DRIVER_LAT_PORT     1
#define PIN_LED_DRIVER_SIN_PORT   1
#define PIN_LED_DRIVER_SCK_PORT   1
#define PIN_BUTTON_PORT 1



#endif